### ISSUE TITLE
Is the train_A and test_A(train_B and test_B) are the same data in SPGAN?

### ISSUE THREAD

**Issue by geyutang** [Simon4Yan/eSPGAN#4]
Hi Weijian,
Thanks for your released code and your SPGAN work.
I got confused about the data preparation process. Is the train_A and test_A(train_B and test_B) are the same data in SPGAN? As to the person re-ID dataset, the style transfer is performed during training and training a discriminate model on both re-ID datasets and style transferred datasets.
Thank for your kindly reply.

**Comment by Simon4Yan** [comment]
Hi!

Good day to you!

The first question--> Yes. Training and testing datasets are the same.

The second question--> In fact, I have tried three ways to train a Reid model, 1) using translated images only; 2) using both translated images and original source images; 3) using translated images to fine-tune the model trained on the original images. The results are similar, so we only use the translated images for training.  

Hope this message is helpful for you!

**Comment by geyutang** [comment]
Thank you, it does help me a lot!
