### ISSUE TITLE
How testing the re-ID  performance

### ISSUE THREAD

**Issue by sunxia233** [Simon4Yan/eSPGAN#6]
Thanks for sharing the code. How do you test the re-ID model? I found that the IDE adds a classifier directly after the output of resnet. Is this classifier removed directly for testing?

**Comment by Simon4Yan** [comment]
Thanks for your attention.

You can use the test code in https://github.com/Simon4Yan/Person_reID_baseline_pytorch.

I am really busy in challenge and paper, and I forget upload the test code for eSPGAN.
Cheers!
