### ISSUE TITLE
一些关于 espgan and spgan区别的疑惑

### ISSUE THREAD

**Issue by yyang-2018** [Simon4Yan/eSPGAN#8]
您好！很荣幸拜读您的论文，我现在有一些关于espgan和spgan区别的疑惑，看了代码后，我发现您在espgan.py里没有使用孪生网络，当然也没有使用论文中的对比损失函数来训练它，直接用一个训练好的基准网络代替，那么espgan不就无法实现spgan 中的相似度保留，不知我理解的是否有偏差，也希望您能告诉我他们俩之间的根本区别，期待您的回复！

**Comment by Simon4Yan** [comment]
感谢关注。eSPGAN 直接用额外的分类器的损失来约束生成器，也就是生成器生成的样本，需要能够被分类器分对，也就是和identity有关的信息能够保留。这种方式和SPGAN的方式还不太一样。

**Comment by yyang-2018** [comment]
感谢您的回复，我现在的理解是，就是将原来孪生网络保证相似性换成一个分类器，这个分类器类似于基准网络训练时的二分类判别做法，换句话说，就是使用分类器来约束，是要比孪生网络效果好一点？虽然我测试下来两个结果差不多，期待您的再次回复！

**Comment by Simon4Yan** [comment]
你说的这个做法和eSPGAN有啥本质区别吗？不都是一样的方式吗？

**Comment by yyang-2018** [comment]
嗯嗯，本质上是一样的，我之前不是很理解espgan和spgan的区别，现在明白了，谢谢您的回复！
